[meta]
name = "Copium"
author = "Ezio"
category = "Race"
version = "1.4.0"
siteid = 500

[script]
dependencies = [ "VehicleState", "MLFeedRaceData" ]
optional_dependencies = [ "ChampionMedals", "UltimateMedalsExtended", "WarriorMedals" ]
